name: Feature Request
description: Suggest an idea for DAM
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please check or start a [Discussion](https://github.com/ez945y/DAM/discussions) before opening an issue.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is your idea?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do we need this?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should it work?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other info or screenshots? (Drag and drop images here)
