#!/usr/bin/env bash
# ── dam-compose.sh ────────────────────────────────────────────────────────
# Stackfile-aware wrapper around `docker compose`.
#
# What it does
# ------------
# 1. Reads hardware.usb_devices from a DAM Stackfile (YAML).
# 2. Generates docker-compose.override.yml with the correct `devices:` entries
#    for the target service (default: api-lerobot).
# 3. Runs `docker compose [your args]` with the override active.
#
# Usage
# -----
#   ./scripts/dam-compose.sh [OPTIONS] -- [DOCKER COMPOSE ARGS]
#
#   Options:
#     --stackfile FILE    Path to DAM Stackfile YAML (default: stackfile.yaml)
#     --service SERVICE   Compose service to add devices to (default: api-lerobot)
#     --dry-run           Print the generated override without running compose
#     -h, --help          Show this help
#
# Examples
# --------
#   # Start LeRobot service with USB devices from Stackfile
#   ./scripts/dam-compose.sh --stackfile examples/stackfiles/so101_act_pick_place.yaml \
#       -- --profile lerobot up -d api-lerobot
#
#   # Preview override YAML without running compose
#   ./scripts/dam-compose.sh --stackfile examples/stackfiles/so101_act_pick_place.yaml --dry-run
#
# Stackfile hardware.usb_devices format
# ---------------------------------------
#   hardware:
#     preset: so101_follower
#     usb_devices:
#       - host: /dev/ttyACM0        # path on your host machine
#         container: /dev/ttyACM0   # path inside the container (usually same)
#       - host: /dev/video0
#         container: /dev/video0
#
# Requirements
# ------------
#   bash >= 4, python3 (for YAML parsing — avoids yq dependency)
# ─────────────────────────────────────────────────────────────────────────

set -euo pipefail

STACKFILE=".dam_stackfile.yaml"
SERVICE="engine-lerobot"
DRY_RUN=false
COMPOSE_ARGS=()

# ── Argument parsing ──────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --stackfile)  STACKFILE="$2"; shift 2 ;;
        --service)    SERVICE="$2";   shift 2 ;;
        --dry-run)    DRY_RUN=true;   shift   ;;
        -h|--help)
            sed -n '2,50p' "$0" | grep '^#' | sed 's/^# \?//'
            exit 0
            ;;
        --)           shift; COMPOSE_ARGS+=("$@"); break ;;
        *)            COMPOSE_ARGS+=("$1"); shift ;;
    esac
done

# ── Validate stackfile ────────────────────────────────────────────────────
if [[ ! -f "$STACKFILE" ]]; then
    echo "[dam-compose] ERROR: Stackfile not found: $STACKFILE" >&2
    echo "  Use --stackfile <path> to specify the Stackfile." >&2
    exit 1
fi

# ── Extract USB devices using Python ─────────────────────────────────────
# Pure Python YAML parsing — no yq / jq dependency required.
DEVICES_JSON=$(python3 - <<PYEOF
import sys, json
try:
    import yaml
except ImportError:
    print("[]"); sys.exit(0)

with open("${STACKFILE}") as f:
    cfg = yaml.safe_load(f)

hw = cfg.get("hardware", {})
devs = hw.get("usb_devices", [])
result = []
for d in devs:
    if isinstance(d, dict):
        host      = d.get("host", "")
        container = d.get("container", host)
        if host:
            result.append({"host": host, "container": container})
    elif isinstance(d, str):
        result.append({"host": d, "container": d})

print(json.dumps(result))
PYEOF
)

# ── Generate override YAML ────────────────────────────────────────────────
OVERRIDE_FILE="docker-compose.override.yml"

python3 - <<PYEOF
import json, sys

devices = json.loads("""${DEVICES_JSON}""")

if not devices:
    print("[dam-compose] No usb_devices found in hardware section — skipping override.")
    sys.exit(0)

lines = [
    "# Auto-generated by scripts/dam-compose.sh — do not edit manually",
    "# Source: ${STACKFILE}",
    "services:",
    "  ${SERVICE}:",
    "    devices:",
]
for d in devices:
    lines.append(f"      - {d['host']}:{d['container']}")

content = "\n".join(lines) + "\n"

with open("${OVERRIDE_FILE}", "w") as f:
    f.write(content)

print(f"[dam-compose] Generated {len(devices)} device(s) in ${OVERRIDE_FILE}:")
for d in devices:
    print(f"  {d['host']} → {d['container']}")
PYEOF

# ── Dry run: just print the override ─────────────────────────────────────
if $DRY_RUN; then
    echo ""
    echo "── ${OVERRIDE_FILE} ──"
    cat "${OVERRIDE_FILE}" 2>/dev/null || echo "(no override generated)"
    echo ""
    echo "[dam-compose] --dry-run: docker compose NOT executed."
    exit 0
fi

# ── Run docker compose ────────────────────────────────────────────────────
if [[ ${#COMPOSE_ARGS[@]} -eq 0 ]]; then
    echo "[dam-compose] No docker compose args given.  Use -- to pass args:"
    echo "  $0 --stackfile ${STACKFILE} -- --profile lerobot up -d ${SERVICE}"
    exit 0
fi

echo "[dam-compose] Running: docker compose ${COMPOSE_ARGS[*]}"
exec docker compose "${COMPOSE_ARGS[@]}"
